name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: pokoinikrws

    steps:
    - name: Clone repo
      uses: actions/checkout@master
      with:
        repository: purecode/astrology-api

    #- name: Install dependencies
    #  run: cd /srv/astrology-api/ && npm install

    #- name: Restart service
    #  run: systemctl restart astrology-api

